@api = http://localhost:3000/api/users

GET {{api}}

###

POST {{api}}
Content-Type: application/json

{
    "userId": "",
    "userName": "victorsigma",
    "password": "Pato123",
    "userMail": "victorossielgaray1@gmail.com",
    "phoneNumber": "4181121125"
}

###

POST {{api}}
Content-Type: application/json

{
    "userId": "",
    "userName": "Sigma",
    "password": "megaman123",
    "userMail": "test2@gmail.com",
    "phoneNumber": "4181121123"
}

###

DELETE {{api}}/70fb7a17-16a4-4e0d-be40-dbbd16ea159e


###

PUT {{api}}/70fb7a17-16a4-4e0d-be40-dbbd16ea159d
Content-Type: application/json

{
    "userId": "70fb7a17-16a4-4e0d-be40-dbbd16ea159d",
    "userName": "Sigma",
    "password": "U2FsdGVkX19Vo1g5EFxWaNkFeBUB6pnnZPb29kG5dj0=",
    "userMail": "test@gmail.com",
    "phoneNumber": "4181121125"
}